name: Manga Recommendation

on:
  schedule:
  #   10:00 AM
  #   12:00 PM
  #   5:00 PM
  #   10:00 PM
  #   12:00 AM (midnight) Philippine time
    - cron: "0 2,4,9,14,16 * * *"

  workflow_dispatch:

jobs:
  manga-recommendation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Post random manga recommendation
        env:
          FB_USER_TOKEN: ${{ secrets.FB_USER_TOKEN }}
        run: |
          python src/main.py